version: "3.7"

services:
  front:
    container_name: me
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - me

networks:
  me:
    driver: bridge
